import type { Metadata } from "next";
import Link from "next/link";
import { getLocale, getTranslations } from "next-intl/server";
import { ComingSoonNotice } from "@/components/ui/ComingSoonNotice";

type Locale="uk"|"pl"|"en"|"de"|"ru";
const COPY={
uk:{badge:"Скоро",eyebrow:"Майбутній ритуал добра",title:"Нехай важлива дата залишить після себе добро",intro:"У майбутньому HappyDate допоможе присвятити день народження чи іншу подію перевіреній добрій справі — тихо, прозоро й з повагою до всіх людей.",soonTitle:"«Подаруй добро» ще готується",soonText:"Ми поки не приймаємо пожертви або заявки й не співпрацюємо від імені фондів. Перед запуском маємо перевірити організації, платежі, звітність і правила використання історій та зображень.",directionsTitle:"Напрями, які ми досліджуємо",directions:[["🐾","Допомога тваринам","Підтримка перевірених притулків і конкретних потреб."],["🤍","Турбота про людей","Допомога через організації, які працюють відповідально й професійно."],["🌿","Турбота про планету","Невеликі зрозумілі дії з підтвердженим результатом."]],flowTitle:"Яким має бути шлях доброї справи",steps:[["Оберіть сенс","Подія стає приводом підтримати близьку вам тему."],["Побачте перевірені потреби","HappyDate показує лише підтверджені організації та призначення допомоги."],["Дійте прозоро","До платежу видно отримувача, комісію та спосіб використання коштів."],["Отримайте підтвердження","Результат зберігається як теплий спогад, без перебільшених обіцянок."]],trustTitle:"Наші незмінні правила",trust:["Жодних неперевірених зборів","Жодних прихованих комісій","Згода на історії та зображення","Звіт про передачу допомоги","Можливість звернення і повернення за правилами"],close:"Добро не повинно бути декорацією. Воно має бути справжнім, перевіреним і людяним."},
pl:{badge:"Wkrótce",eyebrow:"Przyszły rytuał dobra",title:"Niech ważna data pozostawi po sobie dobro",intro:"W przyszłości HappyDate pomoże poświęcić urodziny lub inną okazję sprawdzonej dobrej sprawie — spokojnie, przejrzyście i z szacunkiem.",soonTitle:"„Podaruj dobro” jest jeszcze przygotowywane",soonText:"Nie przyjmujemy obecnie darowizn ani zgłoszeń i nie działamy w imieniu fundacji. Przed startem zweryfikujemy organizacje, płatności, raportowanie oraz prawa do historii i wizerunku.",directionsTitle:"Kierunki, które badamy",directions:[["🐾","Pomoc zwierzętom","Wsparcie zweryfikowanych schronisk i konkretnych potrzeb."],["🤍","Troska o ludzi","Pomoc przez organizacje działające odpowiedzialnie i profesjonalnie."],["🌿","Troska o planetę","Małe, zrozumiałe działania z potwierdzonym rezultatem."]],flowTitle:"Jak powinna wyglądać droga dobra",steps:[["Wybierz znaczenie","Okazja staje się powodem, by wesprzeć bliski temat."],["Zobacz sprawdzone potrzeby","HappyDate pokazuje tylko potwierdzone organizacje i cele."],["Działaj przejrzyście","Przed płatnością znasz odbiorcę, opłatę i sposób użycia środków."],["Otrzymaj potwierdzenie","Rezultat zostaje ciepłym wspomnieniem, bez przesadnych obietnic."]],trustTitle:"Nasze niezmienne zasady",trust:["Żadnych niezweryfikowanych zbiórek","Żadnych ukrytych opłat","Zgoda na historie i wizerunek","Potwierdzenie przekazania pomocy","Jasna ścieżka zgłoszeń i zwrotów"],close:"Dobro nie może być dekoracją. Musi być prawdziwe, sprawdzone i ludzkie."},
en:{badge:"Coming soon",eyebrow:"A future ritual of good",title:"Let an important date leave something good behind",intro:"In the future, HappyDate will help dedicate a birthday or another occasion to a verified cause — quietly, transparently and respectfully.",soonTitle:"Give Good is still in preparation",soonText:"We do not currently accept donations or applications, and we do not act on behalf of charities. Before launch, we must verify organizations, payments, reporting and rights to stories and images.",directionsTitle:"Directions we are exploring",directions:[["🐾","Helping animals","Supporting verified shelters and specific needs."],["🤍","Caring for people","Help through responsible, professional organizations."],["🌿","Caring for the planet","Small, clear actions with a verified result."]],flowTitle:"How a good deed should travel",steps:[["Choose meaning","Turn an occasion into support for a cause close to you."],["See verified needs","HappyDate shows only confirmed organizations and purposes."],["Act transparently","Know the recipient, fees and use of funds before payment."],["Receive confirmation","Keep the result as a warm memory without inflated promises."]],trustTitle:"Our non-negotiable rules",trust:["No unverified campaigns","No hidden fees","Consent for stories and images","Proof that help was transferred","A clear complaint and refund path"],close:"Good should not be decoration. It must be real, verified and humane."},
de:{badge:"Demnächst",eyebrow:"Ein künftiges Ritual des Guten",title:"Lass ein wichtiges Datum etwas Gutes hinterlassen",intro:"Künftig hilft HappyDate, einen Geburtstag oder Anlass einer geprüften guten Sache zu widmen — ruhig, transparent und respektvoll.",soonTitle:"„Gutes schenken“ wird noch vorbereitet",soonText:"Wir nehmen derzeit keine Spenden oder Anträge an und handeln nicht im Namen von Organisationen. Vor dem Start prüfen wir Organisationen, Zahlungen, Berichte sowie Rechte an Geschichten und Bildern.",directionsTitle:"Bereiche, die wir untersuchen",directions:[["🐾","Tieren helfen","Geprüfte Tierheime und konkrete Bedürfnisse unterstützen."],["🤍","Menschen unterstützen","Hilfe über verantwortungsvoll arbeitende Organisationen."],["🌿","Den Planeten schützen","Kleine klare Handlungen mit bestätigtem Ergebnis."]],flowTitle:"So soll eine gute Tat wirken",steps:[["Bedeutung wählen","Einen Anlass nutzen, um ein nahes Thema zu unterstützen."],["Geprüfte Bedarfe sehen","Nur bestätigte Organisationen und Zwecke anzeigen."],["Transparent handeln","Empfänger, Gebühren und Mittelverwendung vor Zahlung kennen."],["Bestätigung erhalten","Das Ergebnis ohne übertriebene Versprechen als Erinnerung bewahren."]],trustTitle:"Unsere unverhandelbaren Regeln",trust:["Keine ungeprüften Sammlungen","Keine versteckten Gebühren","Einwilligung für Geschichten und Bilder","Nachweis der Hilfeleistung","Klare Beschwerden und Erstattungen"],close:"Gutes darf keine Dekoration sein. Es muss echt, geprüft und menschlich sein."},
ru:{badge:"Скоро",eyebrow:"Будущий ритуал добра",title:"Пусть важная дата оставит после себя добро",intro:"В будущем HappyDate поможет посвятить день рождения или другое событие проверенному доброму делу — спокойно, прозрачно и уважительно.",soonTitle:"«Подари добро» ещё готовится",soonText:"Мы пока не принимаем пожертвования или заявки и не действуем от имени фондов. До запуска проверим организации, платежи, отчётность и права на истории и изображения.",directionsTitle:"Направления, которые мы изучаем",directions:[["🐾","Помощь животным","Поддержка проверенных приютов и конкретных потребностей."],["🤍","Забота о людях","Помощь через ответственные профессиональные организации."],["🌿","Забота о планете","Небольшие понятные действия с подтверждённым результатом."]],flowTitle:"Каким должен быть путь доброго дела",steps:[["Выберите смысл","Событие становится поводом поддержать близкую тему."],["Увидьте проверенные потребности","HappyDate показывает только подтверждённые организации и цели."],["Действуйте прозрачно","До оплаты видны получатель, комиссия и использование средств."],["Получите подтверждение","Результат сохраняется как воспоминание без громких обещаний."]],trustTitle:"Наши неизменные правила",trust:["Никаких непроверенных сборов","Никаких скрытых комиссий","Согласие на истории и изображения","Отчёт о передаче помощи","Понятный порядок обращений и возвратов"],close:"Добро не должно быть декорацией. Оно должно быть настоящим, проверенным и человечным."}
} satisfies Record<Locale,{badge:string;eyebrow:string;title:string;intro:string;soonTitle:string;soonText:string;directionsTitle:string;directions:string[][];flowTitle:string;steps:string[][];trustTitle:string;trust:string[];close:string}>;

export async function generateMetadata():Promise<Metadata>{const t=await getTranslations("static.services.phase3b.goodDeed");return{title:t("metaTitle"),description:t("metaDescription"),alternates:{canonical:"/services/podaruj-dobro"},robots:{index:true,follow:true}}}

export default async function GoodDeedPage(){const locale=(await getLocale()) as Locale;const c=COPY[locale]??COPY.uk;const common=await getTranslations("static.services.phase3b");return <main className="good-preview">
<section className="good-preview__hero"><Link href="/services">← {common("backToServices")}</Link><div className="good-preview__heart" aria-hidden="true">♥</div><p>{c.eyebrow}</p><h1>{c.title}</h1><div>{c.intro}</div></section>
<div className="good-preview__body"><ComingSoonNotice badge={c.badge} title={c.soonTitle} description={c.soonText}/>
<section className="good-preview__directions"><h2>{c.directionsTitle}</h2><div>{c.directions.map(([icon,title,text])=><article key={title}><span>{icon}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
<section className="good-preview__flow"><h2>{c.flowTitle}</h2>{c.steps.map(([title,text],i)=><article key={title}><b>{String(i+1).padStart(2,"0")}</b><div><h3>{title}</h3><p>{text}</p></div></article>)}</section>
<section className="good-preview__trust"><h2>🛡️ {c.trustTitle}</h2><ul>{c.trust.map(x=><li key={x}>✓ {x}</li>)}</ul></section><blockquote>“{c.close}”</blockquote></div></main>}
