import type { AppLocale } from "./config";
export const settingsPlanLabels: Record<AppLocale, string> = { uk: "Тарифний план", en: "Plan", pl: "Plan", ru: "Тарифный план", de: "Tarifplan" };
export const settingsAccountLabels: Record<AppLocale, { group: string; pause: string; pauseDescription: string; deleteDescription: string }> = { uk: { group: "Керування акаунтом", pause: "Зробити паузу", pauseDescription: "Тимчасово призупинити HappyDate", deleteDescription: "Назавжди видалити акаунт і дані" }, en: { group: "Account management", pause: "Pause HappyDate", pauseDescription: "Temporarily pause HappyDate", deleteDescription: "Permanently delete your account and data" }, pl: { group: "Zarządzanie kontem", pause: "Wstrzymaj HappyDate", pauseDescription: "Tymczasowo wstrzymaj HappyDate", deleteDescription: "Usuń konto i dane na zawsze" }, ru: { group: "Управление аккаунтом", pause: "Приостановить HappyDate", pauseDescription: "Временно приостановить HappyDate", deleteDescription: "Навсегда удалить аккаунт и данные" }, de: { group: "Kontoverwaltung", pause: "HappyDate pausieren", pauseDescription: "HappyDate vorübergehend pausieren", deleteDescription: "Konto und Daten dauerhaft löschen" } };
export const settingsUi: Record<AppLocale, { groups: string[]; rows: string[]; values: { free: string; language: string }; pause: string; pauseDescription: string; deleteDescription: string }> = {
  uk: { groups: ["Ваш HappyDate", "Акаунт", "Приватність і безпека", "Дані", "Застосунок", "Керування акаунтом"], rows: ["Сповіщення та нагадування", "Happy та персоналізація", "Особисті дані", "Email", "Змінити пароль", "Приватність", "Безпека та вхід", "Активні сеанси", "Мої дані", "Мова"], values: { free: "Free", language: "Українська" }, pause: "Зробити паузу", pauseDescription: "Тимчасово призупинити HappyDate", deleteDescription: "Назавжди видалити акаунт і дані" },
  en: { groups: ["Your HappyDate", "Account", "Privacy and security", "Data", "App", "Account management"], rows: ["Notifications and reminders", "Happy and personalization", "Personal details", "Email", "Change password", "Privacy", "Security and sign-in", "Active sessions", "My data", "Language"], values: { free: "Free", language: "English" }, pause: "Pause HappyDate", pauseDescription: "Temporarily pause HappyDate", deleteDescription: "Permanently delete your account and data" },
  pl: { groups: ["Twój HappyDate", "Konto", "Prywatność i bezpieczeństwo", "Dane", "Aplikacja", "Zarządzanie kontem"], rows: ["Powiadomienia i przypomnienia", "Happy i personalizacja", "Dane osobowe", "Email", "Zmień hasło", "Prywatność", "Bezpieczeństwo i logowanie", "Aktywne sesje", "Moje dane", "Język"], values: { free: "Free", language: "Polski" }, pause: "Wstrzymaj HappyDate", pauseDescription: "Tymczasowo wstrzymaj HappyDate", deleteDescription: "Usuń konto i dane na zawsze" },
  ru: { groups: ["Ваш HappyDate", "Аккаунт", "Конфиденциальность и безопасность", "Данные", "Приложение", "Управление аккаунтом"], rows: ["Уведомления и напоминания", "Happy и персонализация", "Личные данные", "Email", "Изменить пароль", "Конфиденциальность", "Безопасность и вход", "Активные сеансы", "Мои данные", "Язык"], values: { free: "Free", language: "Русский" }, pause: "Приостановить HappyDate", pauseDescription: "Временно приостановить HappyDate", deleteDescription: "Навсегда удалить аккаунт и данные" },
  de: { groups: ["Dein HappyDate", "Konto", "Privatsphäre und Sicherheit", "Daten", "App", "Kontoverwaltung"], rows: ["Benachrichtigungen und Erinnerungen", "Happy und Personalisierung", "Persönliche Daten", "E-Mail", "Passwort ändern", "Privatsphäre", "Sicherheit und Anmeldung", "Aktive Sitzungen", "Meine Daten", "Sprache"], values: { free: "Free", language: "Deutsch" }, pause: "HappyDate pausieren", pauseDescription: "HappyDate vorübergehend pausieren", deleteDescription: "Konto und Daten dauerhaft löschen" },
};
