import assert from "node:assert/strict";
import test from "node:test";
const { resolveHappyReasonSources, buildGiftRecommendationBlock, happyUIBlockSchema, taskProgressBlockFromCard } = await import("../src/lib/happy/ui/happyUIBlock.ts");
const ids = { k: "11111111-1111-4111-8111-111111111111", f: "22222222-2222-4222-8222-222222222222", m: "33333333-3333-4333-8333-333333333333", g: "44444444-4444-4444-8444-444444444444", p: "55555555-5555-4555-8555-555555555555", t: "66666666-6666-4666-8666-666666666666", s: "77777777-7777-4777-8777-777777777777" };
const context = { intent: "birthday_gift", user: { locale: "uk", timezone: "UTC" }, knowledge: { likes: [{ id: ids.k, text: "Pottery", importance: 1, kind: "", category: null, polarity: null }], importantFacts: [{ id: ids.f, text: "Lives in Kyiv", importance: 1, kind: "", category: null, polarity: null }] }, memories: [{ id: ids.m, text: "Trip together", epistemicType: "memory", authority: "user" }], gifts: { previous: [{ id: ids.g, title: "Perfume", lifecycle: "given", eventId: null, createdAt: "2026-01-01" }], planned: [{ id: ids.p, title: "Planned", lifecycle: "idea", eventId: null, createdAt: "2026-01-01" }] } };
test("resolves only projection membership with canonical labels", () => { assert.deepEqual(resolveHappyReasonSources(context, [{ type: "knowledge", id: ids.k }, { type: "knowledge", id: ids.f }, { type: "memory", id: ids.m }, { type: "gift", id: ids.g }])?.map(x => [x.sourceType, x.label]), [["preference", "Pottery"], ["fact", "Lives in Kyiv"], ["memory", "Trip together"], ["gift_history", "Perfume"]]); });
test("rejects invented, planned and duplicate provenance", () => { for (const ref of [{ type: "knowledge", id: ids.p }, { type: "memory", id: ids.p }, { type: "gift", id: ids.p }, { type: "gift", id: ids.g }, { type: "gift", id: ids.g }]) { const refs = ref.id === ids.g ? [{ type: "gift", id: ids.g }, ref] : [ref]; assert.equal(resolveHappyReasonSources(context, refs), null); } });
test("gift block owns actions and strict union rejects escape hatches", () => { const block = buildGiftRecommendationBlock({ idea: { title: "Clay class", message: "A thoughtful option", reasonSources: [{ type: "knowledge", id: ids.k }] }, intentContext: context }); assert.deepEqual(block?.actions, ["save", "dismiss", "more_like_this"]); assert.equal(happyUIBlockSchema.safeParse({ ...block, actions: ["delete"] }).success, false); assert.equal(happyUIBlockSchema.safeParse({ ...block, reasoning: "hidden" }).success, false); });
test("task card adapter preserves display state without execution", () => { const card = { id: ids.t, type: "birthday_preparation", title: "Mia", person: { id: ids.k, name: "Mia" }, event: { id: ids.k, date: "2026-12-01", daysUntil: 3 }, status: "active", progress: { completed: 1, total: 6 }, steps: [{ id: ids.s, type: "analyze_context", state: "completed", requiresApproval: false, waitsForUser: false, optional: false }] }; const block = taskProgressBlockFromCard(card); assert.deepEqual(block.actions, ["continue"]); assert.equal(block.steps[0].state, "completed"); assert.equal(card.steps[0].state, "completed"); });
