"use client";

import { useState } from "react";
import { useLocale } from "next-intl";
import { MoreHorizontal, Plus, X } from "lucide-react";
import type { PersonKnowledgeValueViewModel } from "@/lib/people/peopleData.types";
import { addPersonNote, changePersonKnowledgeValue, deletePersonNote } from "@/lib/people/people.loaders";

export function PersonNotesSection({ personId, personName, notes, onChanged }: { personId: string; personName: string; notes: PersonKnowledgeValueViewModel[]; onChanged?: () => void | Promise<void> }) {
  const uk = useLocale() === "uk";
  const [editing, setEditing] = useState<PersonKnowledgeValueViewModel | "new" | null>(null);
  const [value, setValue] = useState("");
  const [actionsFor, setActionsFor] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  async function save() { if (!value.trim()) return; setBusy(true); try { if (editing === "new") await addPersonNote(personId, value); else if (editing) await changePersonKnowledgeValue(personId, editing.id, value); setEditing(null); setValue(""); await onChanged?.(); } finally { setBusy(false); } }
  return <section className="rounded-[2rem] bg-white/90 p-5 shadow-sm sm:p-8"><div className="flex items-start justify-between gap-4"><div><h2 className="text-2xl font-extrabold text-slate-950">{uk ? "Нотатки та спогади" : "Notes and memories"}</h2><p className="mt-1 text-slate-500">{uk ? `Особисті моменти з ${personName}` : `Personal moments with ${personName}`}</p></div><button onClick={() => { setEditing("new"); setValue(""); }} className="min-h-12 rounded-xl bg-sky-600 px-4 font-bold text-white"><Plus className="mr-2 inline h-4 w-4" />{uk ? "Додати" : "Add"}</button></div>
    {notes.length ? <div className="mt-6 divide-y divide-slate-100">{notes.map((note) => <article key={note.id} className="relative py-5 first:pt-0"><div className="flex gap-4"><div className="min-w-0 flex-1"><time className="text-xs font-bold uppercase tracking-wide text-sky-600">{note.capturedAt ? new Intl.DateTimeFormat(uk ? "uk" : "en", { dateStyle: "medium" }).format(new Date(note.capturedAt)) : ""}</time><p className="mt-2 whitespace-pre-wrap leading-7 text-slate-700">{note.value}</p></div><button aria-label={uk ? "Дії з нотаткою" : "Note actions"} aria-expanded={actionsFor === note.id} className="min-h-11 min-w-11 rounded-full hover:bg-slate-100" onClick={() => setActionsFor(actionsFor === note.id ? null : note.id)}><MoreHorizontal className="mx-auto h-5 w-5" /></button></div>{actionsFor === note.id && <div className="absolute right-0 top-12 z-10 w-40 rounded-xl bg-white p-1.5 shadow-xl ring-1 ring-slate-100"><button className="min-h-11 w-full rounded-lg px-3 text-left font-semibold hover:bg-sky-50" onClick={() => { setActionsFor(null); setEditing(note); setValue(note.value); }}>{uk ? "Редагувати" : "Edit"}</button><button className="min-h-11 w-full rounded-lg px-3 text-left font-semibold text-rose-600 hover:bg-rose-50" onClick={() => { setActionsFor(null); if (confirm(uk ? "Видалити цю нотатку?" : "Delete this note?")) void deletePersonNote(personId, note.id).then(() => onChanged?.()); }}>{uk ? "Видалити" : "Delete"}</button></div>}</article>)}</div> : <div className="mt-6 rounded-2xl bg-slate-50 p-8 text-center text-slate-500">{uk ? "Тут ще немає ваших нотаток та спогадів." : "There are no notes or memories here yet."}</div>}
    {editing && <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/35 sm:items-center sm:p-6"><div className="w-full max-w-xl rounded-t-[2rem] bg-white p-5 sm:rounded-[2rem]"><div className="flex items-center justify-between"><h3 className="text-xl font-extrabold">{editing === "new" ? (uk ? "Нова нотатка" : "New note") : (uk ? "Редагувати нотатку" : "Edit note")}</h3><button className="min-h-11 min-w-11" onClick={() => setEditing(null)}><X className="mx-auto" /></button></div><textarea autoFocus rows={8} maxLength={5000} className="mt-4 w-full rounded-2xl border border-slate-200 p-4" value={value} onChange={(event) => setValue(event.target.value)} placeholder={uk ? "Запишіть момент, розмову або думку…" : "Write down a moment, conversation or thought…"} /><button disabled={busy || !value.trim()} onClick={() => void save()} className="mt-4 min-h-12 w-full rounded-xl bg-sky-600 font-bold text-white disabled:opacity-50">{uk ? "Зберегти" : "Save"}</button></div></div>}
  </section>;
}
