import Link from "next/link";
import { getLocale, getTranslations } from "next-intl/server";
import { ComingSoonNotice } from "@/components/ui/ComingSoonNotice";

type Locale = "uk" | "pl" | "en" | "de" | "ru";
const COPY = {
  uk: { badge:"Скоро", eyebrow:"Майбутня спільна турбота", title:"Разом — для важливої людини", intro:"HappyDate допоможе близьким об’єднатися навколо одного подарунка без незручних нагадувань, таблиць і загублених переказів.", soonTitle:"Спільні збори ще не запущені", soonText:"HappyDate зараз не приймає внески, не зберігає платіжні дані й не виводить кошти. Комісії також не визначені. Функція з’явиться лише після юридичної та платіжної перевірки.", demo:"Майбутній вигляд спільної цілі", collected:"Зібрано разом", people:"5 близьких долучилися", flowTitle:"Як це працюватиме", steps:[["Створіть приватну ціль","Оберіть людину, привід і суму — без публічного збору."],["Запросіть своїх людей","Кожен бачитиме умови та сам вирішуватиме, чи долучатися."],["Контролюйте кошти","Статуси внесків, повернення та виплата будуть прозорими."],["Збережіть спогад","Після подарунка історію можна буде пов’язати з профілем людини."]], trustTitle:"До запуску ми зобов’язані забезпечити", trust:["Ліцензованого платіжного партнера","Підтвердження особи організатора","Прозорі комісії до внеску","Повернення й вирішення спорів","Захист від шахрайства та приватність"], note:"Спільна турбота має зближувати людей, а не створювати фінансову невизначеність." },
  pl: { badge:"Wkrótce", eyebrow:"Przyszła wspólna troska", title:"Razem — dla ważnej osoby", intro:"HappyDate pomoże bliskim połączyć siły wokół jednego prezentu bez niezręcznych przypomnień, arkuszy i zagubionych przelewów.", soonTitle:"Wspólne zbiórki nie są jeszcze dostępne", soonText:"HappyDate nie przyjmuje wpłat, nie przechowuje danych płatniczych ani nie wypłaca środków. Prowizje nie są jeszcze ustalone. Funkcja ruszy dopiero po weryfikacji prawnej i płatniczej.", demo:"Przyszły widok wspólnego celu", collected:"Zebrane razem", people:"5 bliskich dołączyło", flowTitle:"Jak to będzie działać", steps:[["Utwórz prywatny cel","Wybierz osobę, okazję i kwotę — bez publicznej zbiórki."],["Zaproś swoich ludzi","Każdy zobaczy zasady i sam zdecyduje, czy dołączyć."],["Kontroluj środki","Statusy wpłat, zwrotów i wypłaty będą przejrzyste."],["Zachowaj wspomnienie","Po wręczeniu prezentu historię będzie można powiązać z profilem osoby."]], trustTitle:"Przed startem musimy zapewnić", trust:["Licencjonowanego operatora płatności","Weryfikację organizatora","Jasne prowizje przed wpłatą","Zwroty i obsługę sporów","Ochronę przed oszustwami i prywatność"], note:"Wspólna troska ma zbliżać ludzi, a nie tworzyć finansową niepewność." },
  en: { badge:"Coming soon", eyebrow:"Future shared care", title:"Together — for someone important", intro:"HappyDate will help loved ones join around one gift without awkward reminders, spreadsheets or lost transfers.", soonTitle:"Group collections are not available yet", soonText:"HappyDate does not accept contributions, store payment details or pay out funds. Fees have not been set. This feature will launch only after legal and payment validation.", demo:"A future shared-goal view", collected:"Collected together", people:"5 loved ones joined", flowTitle:"How it will work", steps:[["Create a private goal","Choose the person, occasion and amount — without a public fundraiser."],["Invite your people","Everyone sees the terms and chooses whether to join."],["Stay in control","Contribution, refund and payout statuses will be transparent."],["Keep the memory","After the gift, connect its story to the person’s profile."]], trustTitle:"Before launch, we must provide", trust:["A licensed payment partner","Organizer identity verification","Fees disclosed before payment","Refunds and dispute handling","Fraud prevention and privacy"], note:"Shared care should bring people closer, not create financial uncertainty." },
  de: { badge:"Demnächst", eyebrow:"Künftige gemeinsame Fürsorge", title:"Gemeinsam — für einen wichtigen Menschen", intro:"HappyDate wird Nahestehenden helfen, sich für ein Geschenk zusammenzutun — ohne unangenehme Erinnerungen, Tabellen oder verlorene Überweisungen.", soonTitle:"Gemeinsame Sammlungen sind noch nicht verfügbar", soonText:"HappyDate nimmt derzeit keine Beiträge an, speichert keine Zahlungsdaten und zahlt kein Geld aus. Gebühren stehen noch nicht fest. Der Start erfolgt erst nach rechtlicher und technischer Prüfung.", demo:"Künftige Ansicht des gemeinsamen Ziels", collected:"Gemeinsam gesammelt", people:"5 Nahestehende machen mit", flowTitle:"So wird es funktionieren", steps:[["Privates Ziel erstellen","Person, Anlass und Betrag wählen — ohne öffentliche Sammlung."],["Menschen einladen","Alle sehen die Bedingungen und entscheiden selbst."],["Gelder im Blick behalten","Beiträge, Erstattungen und Auszahlung werden transparent."],["Erinnerung bewahren","Die Geschichte des Geschenks mit dem Personenprofil verbinden."]], trustTitle:"Vor dem Start müssen wir gewährleisten", trust:["Lizenzierten Zahlungsanbieter","Identitätsprüfung des Organisators","Gebühren vor der Zahlung","Erstattungen und Streitklärung","Betrugsschutz und Privatsphäre"], note:"Gemeinsame Fürsorge soll verbinden, nicht finanzielle Unsicherheit schaffen." },
  ru: { badge:"Скоро", eyebrow:"Будущая совместная забота", title:"Вместе — для важного человека", intro:"HappyDate поможет близким объединиться ради одного подарка без неловких напоминаний, таблиц и потерянных переводов.", soonTitle:"Совместные сборы ещё не запущены", soonText:"HappyDate пока не принимает взносы, не хранит платёжные данные и не выводит средства. Комиссии тоже не определены. Функция появится только после юридической и платёжной проверки.", demo:"Будущий вид общей цели", collected:"Собрано вместе", people:"5 близких присоединились", flowTitle:"Как это будет работать", steps:[["Создайте приватную цель","Выберите человека, повод и сумму — без публичного сбора."],["Пригласите своих людей","Каждый увидит условия и сам решит, участвовать ли."],["Контролируйте средства","Статусы взносов, возврата и выплаты будут прозрачными."],["Сохраните воспоминание","После подарка историю можно будет связать с профилем человека."]], trustTitle:"До запуска мы обязаны обеспечить", trust:["Лицензированного платёжного партнёра","Проверку личности организатора","Комиссии до момента взноса","Возвраты и разрешение споров","Защиту от мошенничества и приватность"], note:"Совместная забота должна сближать людей, а не создавать финансовую неопределённость." },
} satisfies Record<Locale, {badge:string;eyebrow:string;title:string;intro:string;soonTitle:string;soonText:string;demo:string;collected:string;people:string;flowTitle:string;steps:string[][];trustTitle:string;trust:string[];note:string}>;

function JarPreview() {
  return <div className="fund-preview__jar" aria-hidden="true"><div className="fund-preview__lid"/><div className="fund-preview__glass"><div className="fund-preview__fill"><span>72%</span></div><i>♥</i></div></div>;
}

export default async function FundPage() {
  const locale = (await getLocale()) as Locale;
  const c = COPY[locale] ?? COPY.uk;
  const common = await getTranslations("static.services.phase3b");
  return <main className="fund-preview">
    <section className="fund-preview__hero">
      <Link href="/services">← {common("backToServices")}</Link>
      <p>{c.eyebrow}</p><h1>{c.title}</h1><div>{c.intro}</div>
    </section>
    <div className="fund-preview__body">
      <ComingSoonNotice badge={c.badge} title={c.soonTitle} description={c.soonText}/>
      <section className="fund-preview__demo"><JarPreview/><div><small>{c.demo}</small><h2>{c.collected}</h2><div className="fund-preview__avatars"><span>👩🏻</span><span>👨🏽</span><span>👩🏼</span><span>👨🏻</span><span>👵🏻</span></div><p>{c.people}</p></div></section>
      <section className="fund-preview__flow"><h2>{c.flowTitle}</h2><div>{c.steps.map(([title,text],i)=><article key={title}><b>{i+1}</b><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="fund-preview__trust"><h2>🛡️ {c.trustTitle}</h2><ul>{c.trust.map(x=><li key={x}>✓ {x}</li>)}</ul></section>
      <blockquote>“{c.note}”</blockquote>
    </div>
  </main>;
}
